"""Initial schema

Revision ID: 0c517a4306c6
Revises: 
Create Date: 2026-04-27 22:35:47.543970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c517a4306c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('honesty_codings')
    op.drop_table('messages')
    op.drop_table('questionnaire_responses')
    op.drop_table('participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_responses',
    sa.Column('response_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_submit', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('psych_safe_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psych_safe_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psych_safe_3', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psych_safe_4', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psych_safe_5', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psychological_safety_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('manip_warmth_friendly', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manip_warmth_sincere', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manip_competence_competent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manip_competence_skilled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizational_tenure_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='questionnaire_responses_participant_id_fkey'),
    sa.PrimaryKeyConstraint('response_id', name='questionnaire_responses_pkey'),
    sa.UniqueConstraint('participant_id', name='questionnaire_responses_participant_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('messages',
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('turn_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turn_index_user_only', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turn_index_assistant_only', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('response_latency_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sentence_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follow_up_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='messages_participant_id_fkey'),
    sa.PrimaryKeyConstraint('message_id', name='messages_pkey')
    )
    op.create_table('participants',
    sa.Column('participant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('consent_given', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('forced_condition', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp_session_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_chat_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_chat_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_questionnaire_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_questionnaire_submit', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completion_stage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dropout_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chat_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('questionnaire_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('session_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_turns', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_user_words', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_assistant_words', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('participant_id', name='participants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('honesty_codings',
    sa.Column('coding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coder_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specificity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('riskiness', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_honesty_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('coding_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_coded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='honesty_codings_participant_id_fkey'),
    sa.PrimaryKeyConstraint('coding_id', name='honesty_codings_pkey'),
    sa.UniqueConstraint('participant_id', 'coder_id', name='honesty_codings_participant_id_coder_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
